language: python

python:
  - 2.7

sudo: false

cache:
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - gfortran-5

before_install:
  - pip install codecov
  - git submodule update --init --recursive

install:
  - export FC=/usr/bin/gfortran-5
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE_COMMAND=/usr/bin/gcov-5 ..

script:
  - ctest -VV -T Start -T Build -T Test -T Coverage

after_success:
  - codecov

after_script:
  - cd ..
  - rm -rf build

os:
  - linux
