language: python

python:
  - 2.7

sudo: false

cache:
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - gfortran-5

before_install:
  - pip install codecov
  - git submodule update --init --recursive

install:
  - export FC=/usr/bin/gfortran-5

before_script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE_COMMAND=/usr/bin/gcov-5 ..

script:
  - ctest -VV -T Start -T Build -T Test -T Coverage

after_success:
  - codecov

after_script:
  - cd ..
  - rm -rf build

os:
  - linux
