language: python

python:
  - 2.7

sudo: false

cache:
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - gfortran-6
      - cmake
      - cmake-data

before_install:
  - pip install codecov
  - git submodule update --init --recursive

install:
  - export FC=gfortran-6
  - export CC=gcc-6
  - export GCOV=$(which gcov-6)
  - $FC --version
  - $GCOV --version
  - cmake --version

before_script:
  - mkdir build
  - cd build
  - cmake -DFPL_ENABLE_TESTS=ON -DFPL_ENABLE_EXAMPLES=ON -DCOVERAGE_COMMAND=$GCOV ..

script:
  - ctest -VV -T Start -T Build -T Test #-T Coverage

after_success:
  - find . -name '*.gcno' -print
  - bash <(curl -s https://codecov.io/bash) -x $(GCOV)

after_script:
  - cd ..
  - rm -rf build

os:
  - linux
